#!/bin/zsh
inputDir=$1
fileName=$2
path=$3

container="my_app"
inputFile="/input/$fileName.json"
outFile="/out/$fileName-traj.json"
pythonArgs="-i $inputFile -p $path -o $outFile"
echo $pythonArgs
docker run -it --name $container -d --rm my_image
docker cp $inputDir/$fileName.json $container:$inputFile
docker exec $container python cli.py $pythonArgs
docker cp $container:$outFile $inputDir/$fileName-traj.json
docker stop $container